import { httpClient } from './httpClient';
import { apiRoutes } from './routes';

export const createPlatformApi = (client = httpClient) => ({
  auth: {
    register: (payload) => client.post(apiRoutes.auth.register, payload),
    login: (payload) => client.post(apiRoutes.auth.login, payload),
    logout: () => client.post(apiRoutes.auth.logout),
    refresh: (payload) => client.post(apiRoutes.auth.refresh, payload),
    forgotPassword: (payload) => client.post(apiRoutes.auth.forgotPassword, payload),
    resetPassword: (payload) => client.post(apiRoutes.auth.resetPassword, payload),
    verifyPhone: (payload) => client.post(apiRoutes.auth.verifyPhone, payload),
    verifyEmail: (payload) => client.post(apiRoutes.auth.verifyEmail, payload),
    providers: () => client.get(apiRoutes.auth.providers),
    linkProvider: (provider, payload) => client.post(apiRoutes.auth.providerLink(provider), payload),
    startOtp: (payload) => client.post(apiRoutes.auth.otpStart, payload),
    verifyOtp: (payload) => client.post(apiRoutes.auth.otpVerify, payload),
    sessions: () => client.get(apiRoutes.auth.sessions),
    revokeSession: (id) => client.delete(apiRoutes.auth.session(id)),
    getMe: () => client.get(apiRoutes.auth.me),
    updateMe: (payload) => client.patch(apiRoutes.auth.me, payload),
  },
  verification: {
    levels: () => client.get(apiRoutes.verification.levels),
    me: () => client.get(apiRoutes.verification.me),
    check: (payload) => client.post(apiRoutes.verification.eligibility, payload),
    submitKyc: (payload) => client.post(apiRoutes.verification.submitKyc, payload),
  },
  privacy: {
    get: () => client.get(apiRoutes.privacy.me),
    update: (payload) => client.patch(apiRoutes.privacy.me, payload),
  },
  users: {
    getUser: (id) => client.get(apiRoutes.users.byId(id)),
    updateUser: (id, payload) => client.patch(apiRoutes.users.byId(id), payload),
    listDealers: (query) => client.get(apiRoutes.users.dealerList, { query }),
    getDealer: (id) => client.get(apiRoutes.users.dealer(id)),
    updateDealer: (id, payload) => client.patch(apiRoutes.users.dealer(id), payload),
    verifyDealer: (id, payload) => client.post(apiRoutes.users.verifyDealer(id), payload),
    getDealerListings: (id, query) => client.get(apiRoutes.users.dealerListings(id), { query }),
    getDealerReviews: (id) => client.get(apiRoutes.users.dealerReviews(id)),
    createDealerReview: (id, payload) => client.post(apiRoutes.users.dealerReviews(id), payload),
  },
  listings: {
    list: (query) => client.get(apiRoutes.listings.list, { query }),
    create: (payload) => client.post(apiRoutes.listings.create, payload),
    get: (id) => client.get(apiRoutes.listings.byId(id)),
    update: (id, payload) => client.patch(apiRoutes.listings.byId(id), payload),
    remove: (id) => client.delete(apiRoutes.listings.byId(id)),
    publish: (id) => client.post(apiRoutes.listings.publish(id)),
    archive: (id) => client.post(apiRoutes.listings.archive(id)),
    report: (id, payload) => client.post(apiRoutes.listings.report(id), payload),
    history: (id) => client.get(apiRoutes.listings.history(id)),
    inspection: (id) => client.get(apiRoutes.listings.inspection(id)),
    askQuestion: (id, payload) => client.post(apiRoutes.listings.questions(id), payload),
    makeOffer: (id, payload) => client.post(apiRoutes.listings.offers(id), payload),
  },
  accessories: {
    list: (query) => client.get(apiRoutes.accessories.list, { query }),
    create: (payload) => client.post(apiRoutes.accessories.create, payload),
    get: (id) => client.get(apiRoutes.accessories.byId(id)),
    update: (id, payload) => client.patch(apiRoutes.accessories.byId(id), payload),
    remove: (id) => client.delete(apiRoutes.accessories.byId(id)),
    reviews: (id) => client.get(apiRoutes.accessories.reviews(id)),
    createReview: (id, payload) => client.post(apiRoutes.accessories.reviews(id), payload),
    markReviewHelpful: (id, reviewId) => client.post(apiRoutes.accessories.reviewHelpful(id, reviewId)),
    questions: (id) => client.get(apiRoutes.accessories.questions(id)),
    askQuestion: (id, payload) => client.post(apiRoutes.accessories.questions(id), payload),
    answerQuestion: (id, questionId, payload) => client.post(apiRoutes.accessories.answerQuestion(id, questionId), payload),
    fitment: (id, query) => client.get(apiRoutes.accessories.fitment(id), { query }),
    compatibleWithListing: (listingId) => client.get(apiRoutes.accessories.compatibleWithListing(listingId)),
    wishlist: () => client.get(apiRoutes.accessories.wishlist),
    addWishlist: (id) => client.post(apiRoutes.accessories.wishlistItem(id)),
    removeWishlist: (id) => client.delete(apiRoutes.accessories.wishlistItem(id)),
    garage: () => client.get(apiRoutes.accessories.garage),
    addGarageVehicle: (payload) => client.post(apiRoutes.accessories.garage, payload),
    updateGarageVehicle: (id, payload) => client.patch(apiRoutes.accessories.garageVehicle(id), payload),
    removeGarageVehicle: (id) => client.delete(apiRoutes.accessories.garageVehicle(id)),
  },
  auctions: {
    list: (query) => client.get(apiRoutes.auctions.list, { query }),
    create: (payload) => client.post(apiRoutes.auctions.create, payload),
    get: (id) => client.get(apiRoutes.auctions.byId(id)),
    update: (id, payload) => client.patch(apiRoutes.auctions.byId(id), payload),
    start: (id) => client.post(apiRoutes.auctions.start(id)),
    pause: (id) => client.post(apiRoutes.auctions.pause(id)),
    reopen: (id, payload) => client.post(apiRoutes.auctions.reopen(id), payload),
    end: (id) => client.post(apiRoutes.auctions.end(id)),
    extend: (id, payload) => client.post(apiRoutes.auctions.extend(id), payload),
    status: (id) => client.get(apiRoutes.auctions.status(id)),
    getReserve: (id) => client.get(apiRoutes.auctions.reserve(id)),
    updateReserve: (id, payload) => client.patch(apiRoutes.auctions.reserve(id), payload),
    auditLog: (id) => client.get(apiRoutes.auctions.auditLog(id)),
    watch: (id, payload) => client.post(apiRoutes.auctions.watch(id), payload),
    placeBid: (id, payload) => client.post(apiRoutes.auctions.bids(id), payload),
    bidHistory: (id) => client.get(apiRoutes.auctions.bids(id)),
    myBidStatus: (id) => client.get(apiRoutes.auctions.bidStatus(id)),
    flagBid: (auctionId, bidId, payload) => client.post(apiRoutes.auctions.bidFlag(auctionId, bidId), payload),
    requestBidCancelReview: (auctionId, bidId, payload) => client.post(apiRoutes.auctions.bidCancelReview(auctionId, bidId), payload),
  },
  wallet: {
    summary: () => client.get(apiRoutes.wallet.summary),
    createTopUpIntent: (payload) => client.post(apiRoutes.wallet.topUpIntent, payload),
    requestWithdrawal: (payload) => client.post(apiRoutes.wallet.withdrawalRequest, payload),
    transactions: (query) => client.get(apiRoutes.wallet.transactions, { query }),
    holds: () => client.get(apiRoutes.wallet.holds),
    createHold: (payload) => client.post(apiRoutes.wallet.holds, payload),
    releaseHold: (id, payload) => client.post(apiRoutes.wallet.releaseHold(id), payload),
    forfeitHold: (id, payload) => client.post(apiRoutes.wallet.forfeitHold(id), payload),
  },
  payments: {
    providers: () => client.get(apiRoutes.payments.providers),
    methods: () => client.get(apiRoutes.payments.methods),
    createMethod: (payload) => client.post(apiRoutes.payments.methods, payload),
    transactions: () => client.get(apiRoutes.payments.transactions),
    simulateCallback: (payload) => client.post(apiRoutes.payments.sandboxCallbacks, payload),
  },
  bankPartners: {
    list: () => client.get(apiRoutes.bankPartners.list),
    create: (payload) => client.post(apiRoutes.bankPartners.list, payload),
    update: (id, payload) => client.patch(apiRoutes.bankPartners.byId(id), payload),
  },
  auctionRules: {
    list: () => client.get(apiRoutes.auctionRules.list),
  },
  wishlist: {
    list: () => client.get(apiRoutes.wishlist.list),
    save: (payload) => client.post(apiRoutes.wishlist.list, payload),
    remove: (id) => client.delete(apiRoutes.wishlist.item(id)),
  },
  cart: {
    list: () => client.get(apiRoutes.cart.list),
    add: (payload) => client.post(apiRoutes.cart.items, payload),
    remove: (id) => client.delete(apiRoutes.cart.item(id)),
    history: () => client.get(apiRoutes.cart.history),
  },
  featureSuggestions: {
    list: () => client.get(apiRoutes.featureSuggestions.list),
    create: (payload) => client.post(apiRoutes.featureSuggestions.list, payload),
    adminList: (query) => client.get(apiRoutes.featureSuggestions.adminList, { query }),
    adminUpdate: (id, payload) => client.patch(apiRoutes.featureSuggestions.adminItem(id), payload),
  },
  garageApi: {
    list: () => client.get(apiRoutes.garage.list),
    archive: (id, payload) => client.patch(apiRoutes.garage.archive(id), payload),
  },
  checkout: {
    get: (auctionId) => client.get(apiRoutes.checkout.byAuction(auctionId)),
    start: (auctionId, payload) => client.post(apiRoutes.checkout.start(auctionId), payload),
    update: (auctionId, payload) => client.patch(apiRoutes.checkout.byAuction(auctionId), payload),
    uploadProof: (auctionId, payload) => client.post(apiRoutes.checkout.uploadProof(auctionId), payload),
    confirmPayment: (auctionId, payload) => client.post(apiRoutes.checkout.confirmPayment(auctionId), payload),
    confirmHandover: (auctionId, payload) => client.post(apiRoutes.checkout.confirmHandover(auctionId), payload),
    confirmTitleTransfer: (auctionId, payload) => client.post(apiRoutes.checkout.confirmTitleTransfer(auctionId), payload),
    openDispute: (auctionId, payload) => client.post(apiRoutes.checkout.openDispute(auctionId), payload),
    close: (auctionId, payload) => client.post(apiRoutes.checkout.close(auctionId), payload),
  },
  seller: {
    createSubmission: (payload) => client.post(apiRoutes.seller.submissions, payload),
    listSubmissions: (query) => client.get(apiRoutes.seller.submissions, { query }),
    getSubmission: (id) => client.get(apiRoutes.seller.submission(id)),
    updateSubmission: (id, payload) => client.patch(apiRoutes.seller.submission(id), payload),
    submitForReview: (id) => client.post(apiRoutes.seller.submit(id)),
    createDraft: (payload) => client.post(apiRoutes.seller.drafts, payload),
    listDrafts: () => client.get(apiRoutes.seller.drafts),
    updateDraft: (id, payload) => client.patch(apiRoutes.seller.draft(id), payload),
    deleteDraft: (id) => client.delete(apiRoutes.seller.draft(id)),
    analytics: (query) => client.get(apiRoutes.seller.analytics, { query }),
    listingAnalytics: (id) => client.get(apiRoutes.seller.listingAnalytics(id)),
    payouts: () => client.get(apiRoutes.seller.payouts),
    inventory: () => client.get(apiRoutes.seller.inventory),
    accessoryInventory: () => client.get(apiRoutes.seller.accessoryInventory),
    orders: () => client.get(apiRoutes.seller.orders),
  },
  admin: {
    listSubmissions: (query) => client.get(apiRoutes.admin.submissions, { query }),
    approveSubmission: (id, payload) => client.post(apiRoutes.admin.approveSubmission(id), payload),
    rejectSubmission: (id, payload) => client.post(apiRoutes.admin.rejectSubmission(id), payload),
    requestSubmissionChanges: (id, payload) => client.post(apiRoutes.admin.requestSubmissionChanges(id), payload),
    convertSubmissionToAuction: (id, payload) => client.post(apiRoutes.admin.convertSubmissionToAuction(id), payload),
    reports: (query) => client.get(apiRoutes.admin.reports, { query }),
    resolveReport: (id, payload) => client.post(apiRoutes.admin.resolveReport(id), payload),
    userRisk: (id) => client.get(apiRoutes.admin.userRisk(id)),
    suspendUser: (id, payload) => client.post(apiRoutes.admin.suspendUser(id), payload),
    listingFraudReview: (id, payload) => client.post(apiRoutes.admin.listingFraudReview(id), payload),
    auditLog: (query) => client.get(apiRoutes.admin.auditLog, { query }),
    kycQueue: (query) => client.get(apiRoutes.admin.kycQueue, { query }),
    reviewKyc: (id, payload) => client.post(apiRoutes.admin.kycReview(id), payload),
    documentQueue: (query) => client.get(apiRoutes.admin.documentQueue, { query }),
    reviewDocument: (id, payload) => client.post(apiRoutes.admin.documentReview(id), payload),
    payments: (query) => client.get(apiRoutes.admin.payments, { query }),
    updatePayment: (id, payload) => client.patch(apiRoutes.admin.payment(id), payload),
    bidAudit: (auctionId) => client.get(apiRoutes.admin.bidAudit(auctionId)),
    disputes: (query) => client.get(apiRoutes.admin.disputes, { query }),
    getDispute: (id) => client.get(apiRoutes.admin.dispute(id)),
    updateDispute: (id, payload) => client.patch(apiRoutes.admin.dispute(id), payload),
    accessoryModeration: (query) => client.get(apiRoutes.admin.accessoryModeration, { query }),
    orders: (query) => client.get(apiRoutes.admin.orders, { query }),
  },
  search: {
    listings: (query) => client.get(apiRoutes.search.listings, { query }),
    auctions: (query) => client.get(apiRoutes.search.auctions, { query }),
    suggestions: (query) => client.get(apiRoutes.search.suggestions, { query }),
    facets: (query) => client.get(apiRoutes.search.facets, { query }),
    reindex: () => client.post(apiRoutes.search.reindex),
    saveSearch: (payload) => client.post(apiRoutes.search.savedSearches, payload),
    savedSearches: () => client.get(apiRoutes.search.savedSearches),
    updateSavedSearch: (id, payload) => client.patch(apiRoutes.search.savedSearch(id), payload),
    deleteSavedSearch: (id) => client.delete(apiRoutes.search.savedSearch(id)),
  },
  taxonomy: {
    vehicles: () => client.get(apiRoutes.taxonomy.vehicles),
    makes: () => client.get(apiRoutes.taxonomy.makes),
    models: (make) => client.get(apiRoutes.taxonomy.models(make)),
    variants: (make, model) => client.get(apiRoutes.taxonomy.variants(make, model)),
    accessoryCategories: () => client.get(apiRoutes.taxonomy.accessoryCategories),
    filters: () => client.get(apiRoutes.taxonomy.filters),
  },
  userLists: {
    watchlist: () => client.get(apiRoutes.userLists.watchlist),
    addWatchlist: (listingId) => client.post(apiRoutes.userLists.watchlistItem(listingId)),
    removeWatchlist: (listingId) => client.delete(apiRoutes.userLists.watchlistItem(listingId)),
    compare: () => client.get(apiRoutes.userLists.compare),
    addCompare: (listingId) => client.post(apiRoutes.userLists.compareItem(listingId)),
    removeCompare: (listingId) => client.delete(apiRoutes.userLists.compareItem(listingId)),
    recentlyViewed: () => client.get(apiRoutes.userLists.recentlyViewed),
    trackView: (listingId) => client.post(apiRoutes.userLists.recentlyViewedItem(listingId)),
    bids: () => client.get(apiRoutes.userLists.bids),
    wonAuctions: () => client.get(apiRoutes.userLists.wonAuctions),
  },
  recommendations: {
    home: (query) => client.get(apiRoutes.recommendations.home, { query }),
    auctions: (query) => client.get(apiRoutes.recommendations.auctions, { query }),
    similar: (listingId) => client.get(apiRoutes.recommendations.similar(listingId)),
    deals: (query) => client.get(apiRoutes.recommendations.deals, { query }),
    feedback: (payload) => client.post(apiRoutes.recommendations.feedback, payload),
    events: (query) => client.get(apiRoutes.recommendations.events, { query }),
    trackEvent: (payload) => client.post(apiRoutes.recommendations.events, payload),
    model: (query) => client.get(apiRoutes.recommendations.model, { query }),
    rebuildModel: (payload) => client.post(apiRoutes.recommendations.rebuildModel, payload),
  },
  orders: {
    list: () => client.get(apiRoutes.orders.list),
    create: (payload) => client.post(apiRoutes.orders.create, payload),
    action: (id, action, payload) => client.post(apiRoutes.orders.action(id, action), payload),
  },
  repairShops: {
    list: (query) => client.get(apiRoutes.repairShops.list, { query }),
    rankings: (query) => client.get(apiRoutes.repairShops.rankings, { query }),
    create: (payload) => client.post(apiRoutes.repairShops.create, payload),
    get: (id) => client.get(apiRoutes.repairShops.byId(id)),
    updateSocials: (id, payload) => client.patch(apiRoutes.repairShops.socials(id), payload),
    reviews: (id) => client.get(apiRoutes.repairShops.reviews(id)),
    createReview: (id, payload) => client.post(apiRoutes.repairShops.reviews(id), payload),
    questions: (id) => client.get(apiRoutes.repairShops.questions(id)),
    askQuestion: (id, payload) => client.post(apiRoutes.repairShops.questions(id), payload),
    answerQuestion: (id, questionId, payload) => client.post(apiRoutes.repairShops.answerQuestion(id, questionId), payload),
    videos: (id) => client.get(apiRoutes.repairShops.videos(id)),
    addVideo: (id, payload) => client.post(apiRoutes.repairShops.videos(id), payload),
  },
  ai: {
    features: () => client.get(apiRoutes.ai.features),
    personalizedRecommendations: (query) => client.get(apiRoutes.ai.personalizedRecommendations, { query }),
    pricePrediction: (payload) => client.post(apiRoutes.ai.pricePrediction, payload),
    priceModelStatus: () => client.get(apiRoutes.ai.priceModelStatus),
    priceEstimate: (listingId, payload) => client.post(apiRoutes.ai.priceEstimate(listingId), payload),
    dealScore: (listingId) => client.get(apiRoutes.ai.dealScore(listingId)),
    similarListings: (listingId) => client.get(apiRoutes.ai.similarListings(listingId)),
    auctionWinProbability: (auctionId) => client.get(apiRoutes.ai.auctionWinProbability(auctionId)),
    auctionBidTiming: (auctionId) => client.get(apiRoutes.ai.auctionBidTiming(auctionId)),
    auctionStrategy: (auctionId) => client.get(apiRoutes.ai.auctionStrategy(auctionId)),
    listingQuality: (payload) => client.post(apiRoutes.ai.listingQuality, payload),
    fraudCheck: (payload) => client.post(apiRoutes.ai.fraudCheck, payload),
    naturalLanguageSearch: (payload) => client.post(apiRoutes.ai.naturalLanguageSearch, payload),
    summarizeThread: (payload) => client.post(apiRoutes.ai.summarizeThread, payload),
    moderateCommunity: (payload) => client.post(apiRoutes.ai.moderateCommunity, payload),
    inspectionInsight: (payload) => client.post(apiRoutes.ai.inspectionInsight, payload),
    sellerPricingCoach: (payload) => client.post(apiRoutes.ai.sellerPricingCoach, payload),
  },
  messages: {
    conversations: () => client.get(apiRoutes.messages.conversations),
    createConversation: (payload) => client.post(apiRoutes.messages.conversations, payload),
    conversation: (id) => client.get(apiRoutes.messages.conversation(id)),
    send: (id, payload) => client.post(apiRoutes.messages.messages(id), payload),
    markRead: (id) => client.post(apiRoutes.messages.read(id)),
    report: (id, payload) => client.post(apiRoutes.messages.report(id), payload),
    block: (id, payload) => client.post(apiRoutes.messages.block(id), payload),
  },
  notifications: {
    list: () => client.get(apiRoutes.notifications.list),
    markRead: (id) => client.post(apiRoutes.notifications.read(id)),
    markAllRead: () => client.post(apiRoutes.notifications.readAll),
    updatePreferences: (payload) => client.patch(apiRoutes.notifications.preferences, payload),
    registerPushDevice: (payload) => client.post(apiRoutes.notifications.registerPushDevice, payload),
    removePushDevice: (id) => client.delete(apiRoutes.notifications.pushDevice(id)),
  },
  community: {
    forums: () => client.get(apiRoutes.community.forums),
    createForum: (payload) => client.post(apiRoutes.community.forums, payload),
    forumPosts: (id, query) => client.get(apiRoutes.community.forumPosts(id), { query }),
    createPost: (payload) => client.post(apiRoutes.community.posts, payload),
    getPost: (id) => client.get(apiRoutes.community.post(id)),
    updatePost: (id, payload) => client.patch(apiRoutes.community.post(id), payload),
    deletePost: (id) => client.delete(apiRoutes.community.post(id)),
    votePost: (id, payload) => client.post(apiRoutes.community.votePost(id), payload),
    savePost: (id) => client.post(apiRoutes.community.savePost(id)),
    reportPost: (id, payload) => client.post(apiRoutes.community.reportPost(id), payload),
    addComment: (id, payload) => client.post(apiRoutes.community.comments(id), payload),
    voteComment: (id, payload) => client.post(apiRoutes.community.voteComment(id), payload),
    addReply: (id, payload) => client.post(apiRoutes.community.replies(id), payload),
    markBestAnswer: (id, payload) => client.post(apiRoutes.community.bestAnswer(id), payload),
    faq: () => client.get(apiRoutes.community.faq),
    createFaq: (payload) => client.post(apiRoutes.community.faq, payload),
    updateFaq: (id, payload) => client.patch(apiRoutes.community.faqItem(id), payload),
  },
  articles: {
    list: (query) => client.get(apiRoutes.articles.list, { query }),
    get: (slug) => client.get(apiRoutes.articles.bySlug(slug)),
    create: (payload) => client.post(apiRoutes.articles.create, payload),
    drafts: () => client.get(apiRoutes.articles.drafts),
    updateStatus: (id, payload) => client.patch(apiRoutes.articles.status(id), payload),
    like: (slug) => client.post(apiRoutes.articles.like(slug)),
    bookmark: (slug) => client.post(apiRoutes.articles.bookmark(slug)),
    comments: (slug) => client.get(apiRoutes.articles.comments(slug)),
    addComment: (slug, payload) => client.post(apiRoutes.articles.comments(slug), payload),
  },
  media: {
    createUploadIntent: (payload) => client.post(apiRoutes.media.uploadIntent, payload),
    completeUpload: (payload) => client.post(apiRoutes.media.complete, payload),
    processing: () => client.get(apiRoutes.media.processing),
    deleteMedia: (id) => client.delete(apiRoutes.media.byId(id)),
    moderateMedia: (id, payload) => client.post(apiRoutes.media.moderate(id), payload),
    reorderListingMedia: (listingId, payload) => client.post(apiRoutes.media.reorderListingMedia(listingId), payload),
    createDocumentUploadIntent: (payload) => client.post(apiRoutes.media.documentUploadIntent, payload),
    getDocument: (id) => client.get(apiRoutes.media.document(id)),
    verifyDocument: (id, payload) => client.post(apiRoutes.media.verifyDocument(id), payload),
  },
  trust: {
    verifySeller: (payload) => client.post(apiRoutes.trust.verifySeller, payload),
    verifyBidder: (payload) => client.post(apiRoutes.trust.verifyBidder, payload),
    getKycProfile: () => client.get(apiRoutes.trust.kycProfile),
    submitKycDocument: (payload) => client.post(apiRoutes.trust.submitKycDocument, payload),
    bidderEligibility: (payload) => client.post(apiRoutes.trust.bidderEligibility, payload),
  },
  integrations: {
    socialLogin: (provider, payload) => client.post(apiRoutes.integrations.socialLogin(provider), payload),
    trackShare: (payload) => client.post(apiRoutes.integrations.shareTracking, payload),
    startKyc: (payload) => client.post(apiRoutes.integrations.kycStart, payload),
    decodeVehicle: (payload) => client.post(apiRoutes.integrations.vehicleDecode, payload),
    mapPlaces: (query) => client.get(apiRoutes.integrations.mapPlaces, { query }),
  },
  platform: {
    contracts: () => client.get(apiRoutes.platform.contracts),
    readiness: () => client.get(apiRoutes.platform.readiness),
  },
});

export const platformApi = createPlatformApi();
