export const apiRoutes = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyPhone: '/auth/verify-phone',
    verifyEmail: '/auth/verify-email',
    providers: '/auth/providers',
    providerLink: (provider) => `/auth/providers/${provider}/link`,
    otpStart: '/auth/otp/start',
    otpVerify: '/auth/otp/verify',
    sessions: '/auth/sessions',
    session: (id) => `/auth/sessions/${id}`,
    me: '/me',
  },
  verification: {
    levels: '/verification/levels',
    me: '/verification/me',
    eligibility: '/eligibility/check',
    submitKyc: '/kyc/submit',
  },
  privacy: {
    me: '/privacy/me',
  },
  users: {
    byId: (id) => `/users/${id}`,
    dealerList: '/dealers',
    dealer: (id) => `/dealers/${id}`,
    dealerListings: (id) => `/dealers/${id}/listings`,
    dealerReviews: (id) => `/dealers/${id}/reviews`,
    verifyDealer: (id) => `/dealers/${id}/verify`,
  },
  listings: {
    list: '/listings',
    create: '/listings',
    byId: (id) => `/listings/${id}`,
    publish: (id) => `/listings/${id}/publish`,
    archive: (id) => `/listings/${id}/archive`,
    report: (id) => `/listings/${id}/report`,
    history: (id) => `/listings/${id}/history`,
    inspection: (id) => `/listings/${id}/inspection`,
    questions: (id) => `/listings/${id}/questions`,
    offers: (id) => `/listings/${id}/offers`,
  },
  accessories: {
    list: '/accessories',
    create: '/accessories',
    byId: (id) => `/accessories/${id}`,
    reviews: (id) => `/accessories/${id}/reviews`,
    reviewHelpful: (id, reviewId) => `/accessories/${id}/reviews/${reviewId}/helpful`,
    questions: (id) => `/accessories/${id}/questions`,
    answerQuestion: (id, questionId) => `/accessories/${id}/questions/${questionId}/answer`,
    fitment: (id) => `/accessories/${id}/fitment`,
    compatibleWithListing: (listingId) => `/listings/${listingId}/accessories`,
    wishlist: '/me/accessory-wishlist',
    wishlistItem: (id) => `/me/accessory-wishlist/${id}`,
    garage: '/me/garage',
    garageVehicle: (id) => `/me/garage/${id}`,
  },
  auctions: {
    list: '/auctions',
    create: '/auctions',
    byId: (id) => `/auctions/${id}`,
    start: (id) => `/auctions/${id}/start`,
    pause: (id) => `/auctions/${id}/pause`,
    reopen: (id) => `/auctions/${id}/reopen`,
    end: (id) => `/auctions/${id}/end`,
    extend: (id) => `/auctions/${id}/extend`,
    status: (id) => `/auctions/${id}/status`,
    reserve: (id) => `/auctions/${id}/reserve`,
    auditLog: (id) => `/auctions/${id}/audit-log`,
    bids: (id) => `/auctions/${id}/bids`,
    bidStatus: (id) => `/auctions/${id}/my-bid-status`,
    watch: (id) => `/auctions/${id}/watch`,
    bidFlag: (auctionId, bidId) => `/auctions/${auctionId}/bids/${bidId}/flag`,
    bidCancelReview: (auctionId, bidId) => `/auctions/${auctionId}/bids/${bidId}/cancel-review`,
  },
  wallet: {
    summary: '/wallet',
    topUpIntent: '/wallet/top-up-intent',
    withdrawalRequest: '/wallet/withdrawal-request',
    transactions: '/wallet/transactions',
    holds: '/wallet/holds',
    hold: (id) => `/wallet/holds/${id}`,
    releaseHold: (id) => `/wallet/holds/${id}/release`,
    forfeitHold: (id) => `/wallet/holds/${id}/forfeit`,
    paymentWebhook: '/wallet/webhooks/payment',
    refundWebhook: '/wallet/webhooks/refund',
  },
  payments: {
    providers: '/payments/providers',
    methods: '/payments/methods',
    transactions: '/payments/transactions',
    sandboxCallbacks: '/payments/sandbox/callbacks',
  },
  bankPartners: {
    list: '/bank-partners',
    byId: (id) => `/bank-partners/${id}`,
  },
  auctionRules: {
    list: '/auction-rules',
  },
  wishlist: {
    list: '/wishlist',
    item: (id) => `/wishlist/${id}`,
  },
  cart: {
    list: '/cart',
    items: '/cart/items',
    item: (id) => `/cart/items/${id}`,
    history: '/cart/history',
  },
  featureSuggestions: {
    list: '/feature-suggestions',
    adminList: '/admin/feature-suggestions',
    adminItem: (id) => `/admin/feature-suggestions/${id}`,
  },
  garage: {
    list: '/garage',
    archive: (id) => `/garage/${id}/archive`,
  },
  checkout: {
    byAuction: (auctionId) => `/checkout/${auctionId}`,
    start: (auctionId) => `/checkout/${auctionId}/start`,
    uploadProof: (auctionId) => `/checkout/${auctionId}/upload-proof`,
    confirmPayment: (auctionId) => `/checkout/${auctionId}/confirm-payment`,
    confirmHandover: (auctionId) => `/checkout/${auctionId}/confirm-handover`,
    confirmTitleTransfer: (auctionId) => `/checkout/${auctionId}/confirm-title-transfer`,
    openDispute: (auctionId) => `/checkout/${auctionId}/open-dispute`,
    close: (auctionId) => `/checkout/${auctionId}/close`,
  },
  seller: {
    submissions: '/seller/submissions',
    submission: (id) => `/seller/submissions/${id}`,
    submit: (id) => `/seller/submissions/${id}/submit`,
    drafts: '/seller/drafts',
    draft: (id) => `/seller/drafts/${id}`,
    analytics: '/seller/analytics',
    listingAnalytics: (id) => `/seller/listings/${id}/analytics`,
    payouts: '/seller/payouts',
    inventory: '/seller/inventory',
    accessoryInventory: '/seller/accessory-inventory',
    orders: '/seller/orders',
  },
  admin: {
    submissions: '/admin/submissions',
    approveSubmission: (id) => `/admin/submissions/${id}/approve`,
    rejectSubmission: (id) => `/admin/submissions/${id}/reject`,
    requestSubmissionChanges: (id) => `/admin/submissions/${id}/request-changes`,
    convertSubmissionToAuction: (id) => `/admin/submissions/${id}/convert-to-auction`,
    reports: '/admin/reports',
    resolveReport: (id) => `/admin/reports/${id}/resolve`,
    userRisk: (id) => `/admin/users/${id}/risk`,
    suspendUser: (id) => `/admin/users/${id}/suspend`,
    listingFraudReview: (id) => `/admin/listings/${id}/fraud-review`,
    auditLog: '/admin/audit-log',
    kycQueue: '/admin/kyc',
    kycReview: (id) => `/admin/kyc/${id}/review`,
    documentQueue: '/admin/documents',
    documentReview: (id) => `/admin/documents/${id}/review`,
    payments: '/admin/payments',
    payment: (id) => `/admin/payments/${id}`,
    bidAudit: (auctionId) => `/admin/auctions/${auctionId}/bid-audit`,
    disputes: '/admin/disputes',
    dispute: (id) => `/admin/disputes/${id}`,
    accessoryModeration: '/admin/accessories/moderation',
    orders: '/admin/orders',
  },
  search: {
    listings: '/search/listings',
    auctions: '/search/auctions',
    suggestions: '/search/suggestions',
    facets: '/search/facets',
    reindex: '/search/reindex',
    savedSearches: '/saved-searches',
    savedSearch: (id) => `/saved-searches/${id}`,
  },
  taxonomy: {
    vehicles: '/taxonomy/vehicles',
    makes: '/taxonomy/makes',
    models: (make) => `/taxonomy/makes/${make}/models`,
    variants: (make, model) => `/taxonomy/makes/${make}/models/${model}/variants`,
    accessoryCategories: '/taxonomy/accessory-categories',
    filters: '/taxonomy/filters',
  },
  userLists: {
    watchlist: '/me/watchlist',
    watchlistItem: (listingId) => `/me/watchlist/${listingId}`,
    compare: '/me/compare',
    compareItem: (listingId) => `/me/compare/${listingId}`,
    recentlyViewed: '/me/recently-viewed',
    recentlyViewedItem: (listingId) => `/me/recently-viewed/${listingId}`,
    bids: '/me/bids',
    wonAuctions: '/me/won-auctions',
  },
  recommendations: {
    home: '/recommendations/home',
    auctions: '/recommendations/auctions',
    similar: (listingId) => `/recommendations/similar/${listingId}`,
    deals: '/recommendations/deals',
    feedback: '/recommendations/feedback',
    events: '/recommendations/events',
    model: '/recommendations/model',
    rebuildModel: '/recommendations/rebuild-model',
  },
  orders: {
    list: '/orders',
    create: '/orders',
    action: (id, action) => `/orders/${id}/${action}`,
  },
  repairShops: {
    list: '/repair-shops',
    create: '/repair-shops',
    byId: (id) => `/repair-shops/${id}`,
    socials: (id) => `/repair-shops/${id}/socials`,
    reviews: (id) => `/repair-shops/${id}/reviews`,
    questions: (id) => `/repair-shops/${id}/questions`,
    answerQuestion: (id, questionId) => `/repair-shops/${id}/questions/${questionId}/answer`,
    videos: (id) => `/repair-shops/${id}/videos`,
    rankings: '/rankings/repair-shops',
  },
  ai: {
    features: '/ai/features',
    personalizedRecommendations: '/ai/recommendations/personalized',
    pricePrediction: '/ai/price-prediction',
    priceModelStatus: '/ai/price-model/status',
    priceEstimate: (listingId) => `/ai/listings/${listingId}/price-estimate`,
    dealScore: (listingId) => `/ai/listings/${listingId}/deal-score`,
    similarListings: (listingId) => `/ai/listings/${listingId}/similar`,
    auctionWinProbability: (auctionId) => `/ai/auctions/${auctionId}/win-probability`,
    auctionBidTiming: (auctionId) => `/ai/auctions/${auctionId}/bid-timing`,
    auctionStrategy: (auctionId) => `/ai/auctions/${auctionId}/strategy`,
    listingQuality: '/ai/listings/quality-score',
    fraudCheck: '/ai/listings/fraud-check',
    naturalLanguageSearch: '/ai/search/natural-language',
    summarizeThread: '/ai/community/summarize-thread',
    moderateCommunity: '/ai/community/moderation',
    inspectionInsight: '/ai/inspections/insight',
    sellerPricingCoach: '/ai/seller/pricing-coach',
  },
  messages: {
    conversations: '/conversations',
    conversation: (id) => `/conversations/${id}`,
    messages: (id) => `/conversations/${id}/messages`,
    read: (id) => `/conversations/${id}/read`,
    report: (id) => `/conversations/${id}/report`,
    block: (id) => `/conversations/${id}/block`,
  },
  notifications: {
    list: '/notifications',
    read: (id) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
    preferences: '/notification-preferences',
    registerPushDevice: '/push/register-device',
    pushDevice: (id) => `/push/devices/${id}`,
  },
  community: {
    forums: '/forums',
    forumPosts: (id) => `/forums/${id}/posts`,
    posts: '/posts',
    post: (id) => `/posts/${id}`,
    votePost: (id) => `/posts/${id}/vote`,
    savePost: (id) => `/posts/${id}/save`,
    reportPost: (id) => `/posts/${id}/report`,
    comments: (id) => `/posts/${id}/comments`,
    voteComment: (id) => `/comments/${id}/vote`,
    replies: (id) => `/comments/${id}/replies`,
    bestAnswer: (id) => `/comments/${id}/best-answer`,
    faq: '/faq',
    faqItem: (id) => `/faq/${id}`,
  },
  articles: {
    list: '/articles',
    create: '/articles',
    drafts: '/articles/drafts',
    bySlug: (slug) => `/articles/${slug}`,
    status: (id) => `/articles/${id}/status`,
    like: (slug) => `/articles/${slug}/like`,
    bookmark: (slug) => `/articles/${slug}/bookmark`,
    comments: (slug) => `/articles/${slug}/comments`,
  },
  media: {
    uploadIntent: '/media/upload-intent',
    complete: '/media/complete',
    processing: '/media/processing',
    byId: (id) => `/media/${id}`,
    moderate: (id) => `/media/${id}/moderate`,
    reorderListingMedia: (listingId) => `/listings/${listingId}/media/reorder`,
    documentUploadIntent: '/documents/upload-intent',
    document: (id) => `/documents/${id}`,
    verifyDocument: (id) => `/documents/${id}/verify`,
  },
  trust: {
    verifySeller: '/trust/verify-seller',
    verifyBidder: '/trust/verify-bidder',
    kycProfile: '/trust/kyc-profile',
    submitKycDocument: '/trust/kyc-documents',
    bidderEligibility: '/trust/bidder-eligibility',
  },
  integrations: {
    socialLogin: (provider) => `/integrations/social/${provider}/login`,
    socialCallback: (provider) => `/integrations/social/${provider}/callback`,
    shareTracking: '/integrations/social/share-tracking',
    kycStart: '/integrations/kyc/start',
    kycCallback: '/integrations/kyc/callback',
    smsWebhook: '/integrations/sms/webhook',
    whatsappWebhook: '/integrations/whatsapp/webhook',
    vehicleDecode: '/integrations/vehicle/decode',
    mapPlaces: '/integrations/maps/places',
  },
  platform: {
    contracts: '/platform/contracts',
    readiness: '/platform/readiness',
  },
};
