export const seedData = {
  users: [],
  sessions: [],
  passwordResets: [],
  dealers: [
    {
      id: 'seed-seller',
      userId: 'seed-seller',
      businessName: 'Indus Pre-Owned',
      city: 'Karachi',
      status: 'verified',
      verified: true,
      trustScore: 96,
      membership: { plan: 'monthly_dealer', status: 'active', feePkr: 25000 },
      badges: ['Verified dealer', 'Auction seller'],
      createdAt: new Date().toISOString(),
    },
  ],
  dealerReviews: [],
  kycProfiles: [],
  walletAccounts: [],
  walletLedger: [],
  depositHolds: [],
  paymentIntents: [],
  mediaAssets: [],
  listingMedia: [],
  documentVerifications: [],
  auditLogs: [],
  listings: [
    {
      id: '1',
      listingType: 'auction',
      status: 'live',
      year: 2019,
      make: 'Toyota',
      model: 'Fortuner',
      variant: 'V Petrol',
      bodyStyle: 'SUV',
      powertrain: 'Petrol',
      transmission: 'Automatic',
      mileageKm: 45000,
      city: 'Karachi',
      titleStatus: 'Clean',
      askingPrice: null,
      marketEstimate: 9100000,
      inspectionScore: 91,
      trustScore: 96,
      sellerId: 'seed-seller',
    },
    {
      id: '2',
      listingType: 'auction',
      status: 'live',
      year: 2021,
      make: 'Honda',
      model: 'Civic',
      variant: 'RS Turbo',
      bodyStyle: 'Sedan',
      powertrain: 'Petrol',
      transmission: 'CVT',
      mileageKm: 12000,
      city: 'Lahore',
      titleStatus: 'Clean',
      askingPrice: null,
      marketEstimate: 6600000,
      inspectionScore: 88,
      trustScore: 88,
      sellerId: 'seed-seller',
    },
  ],
  auctions: [
    {
      id: '1',
      listingId: '1',
      status: 'live',
      reservePrice: 8190000,
      highBid: 8500000,
      bidIncrement: 50000,
      lastBidderId: null,
      bidsCount: 0,
      endsAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      extensionsCount: 0,
      winnerId: null,
    },
    {
      id: '2',
      listingId: '2',
      status: 'live',
      reservePrice: 5940000,
      highBid: 6250000,
      bidIncrement: 50000,
      lastBidderId: null,
      bidsCount: 0,
      endsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      extensionsCount: 0,
      winnerId: null,
    },
  ],
  bids: [],
  accessories: [
    {
      id: 'accessory-floor-mats',
      name: 'Fortuner All-Weather Floor Mat Set',
      category: 'Seat Covers & Mats',
      condition: 'new',
      price: 28500,
      city: 'Karachi',
      sellerId: 'seed-seller',
      fitmentType: 'vehicle_specific',
      stock: 12,
      warranty: '6 months',
    },
    {
      id: 'accessory-dashcam',
      name: 'Universal 70mai Dashcam Kit',
      category: 'Dashcams & Cameras',
      condition: 'new',
      price: 42000,
      city: 'Lahore',
      sellerId: 'seed-seller',
      fitmentType: 'universal',
      stock: 22,
      warranty: '1 year',
    },
  ],
  accessoryFitments: [
    {
      id: 'fitment-fortuner-mats',
      accessoryId: 'accessory-floor-mats',
      yearFrom: 2016,
      yearTo: 2024,
      make: 'Toyota',
      model: 'Fortuner',
      bodyStyle: 'SUV',
    },
  ],
  accessoryReviews: [
    {
      id: 'review-floor-mats-1',
      accessoryId: 'accessory-floor-mats',
      userId: 'seed-buyer-1',
      userName: 'Fortuner Owner',
      rating: 5,
      title: 'Fit was accurate',
      body: 'The mat shape matched my Fortuner cabin and the raised edges are useful in rain.',
      fitmentConfirmed: true,
      serviceContext: 'Installed myself',
      helpfulCount: 7,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    },
    {
      id: 'review-dashcam-1',
      accessoryId: 'accessory-dashcam',
      userId: 'seed-buyer-2',
      userName: 'Lahore Buyer',
      rating: 4,
      title: 'Good camera, ask about installation',
      body: 'Video quality is good. Hardwire kit installation should be confirmed with seller before checkout.',
      fitmentConfirmed: true,
      serviceContext: 'Workshop installed',
      helpfulCount: 4,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
  ],
  accessoryQuestions: [
    {
      id: 'question-floor-mats-1',
      accessoryId: 'accessory-floor-mats',
      userId: 'seed-buyer-3',
      userName: 'Karachi Buyer',
      question: 'Does this set include the boot mat or only cabin mats?',
      answer: 'This listing is for cabin mats only. Boot mat can be added as a separate item.',
      answeredBy: 'seed-seller',
      answeredByName: 'Indus Pre-Owned',
      answeredAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      status: 'answered',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    },
    {
      id: 'question-dashcam-1',
      accessoryId: 'accessory-dashcam',
      userId: 'seed-buyer-4',
      userName: 'Civic Owner',
      question: 'Can the seller install this with parking mode in Lahore?',
      status: 'open',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    },
  ],
  repairShops: [
    {
      id: 'repair-clifton-auto-care',
      name: 'Clifton Auto Care',
      category: 'workshops',
      city: 'Karachi',
      area: 'Clifton',
      address: 'Block 5, Clifton, Karachi',
      lat: 24.8138,
      lng: 67.0306,
      distanceKm: 2.4,
      rating: 4.8,
      reviews: 312,
      completedJobs: 1240,
      communityVotes: 486,
      responseTime: '12 min',
      verified: true,
      openNow: true,
      specialties: ['Inspection', 'Oil change', 'Suspension', 'AC repair'],
      socialLinks: { facebook: 'https://facebook.com/cliftonautocare', instagram: 'https://instagram.com/cliftonautocare', whatsapp: 'https://wa.me/923001112233' },
    },
    {
      id: 'repair-dha-hybrid-workshop',
      name: 'Defence Hybrid Workshop',
      category: 'inspection',
      city: 'Karachi',
      area: 'DHA Phase 6',
      address: 'Khayaban-e-Ittehad, DHA Phase 6, Karachi',
      lat: 24.7936,
      lng: 67.0642,
      distanceKm: 4.1,
      rating: 4.7,
      reviews: 226,
      completedJobs: 810,
      communityVotes: 354,
      responseTime: '18 min',
      verified: true,
      openNow: true,
      specialties: ['Hybrid', 'Diagnostics', 'EV check', 'Battery'],
      socialLinks: { website: 'https://example.com/defence-hybrid', youtube: 'https://youtube.com/@defencehybrid' },
    },
    {
      id: 'repair-johar-premium-car-wash',
      name: 'Johar Premium Car Wash',
      category: 'car-wash',
      city: 'Karachi',
      area: 'Gulistan-e-Johar',
      address: 'Block 15, Gulistan-e-Johar, Karachi',
      lat: 24.9263,
      lng: 67.1321,
      distanceKm: 7.5,
      rating: 4.5,
      reviews: 188,
      completedJobs: 1420,
      communityVotes: 228,
      responseTime: '10 min',
      verified: true,
      openNow: true,
      specialties: ['Car wash', 'Detailing', 'Ceramic coating', 'Interior cleaning'],
      socialLinks: { instagram: 'https://instagram.com/joharpremiumwash', tiktok: 'https://tiktok.com/@joharpremiumwash' },
    },
    {
      id: 'repair-lahore-certified-dealership',
      name: 'Lahore Certified Dealership Hub',
      category: 'dealerships',
      city: 'Lahore',
      area: 'Johar Town',
      address: 'Main Boulevard Johar Town, Lahore',
      lat: 31.4697,
      lng: 74.2728,
      distanceKm: 8.4,
      rating: 4.3,
      reviews: 132,
      completedJobs: 520,
      communityVotes: 184,
      responseTime: '30 min',
      verified: true,
      openNow: true,
      specialties: ['Dealership', 'Certified used cars', 'Trade-in', 'Financing'],
      socialLinks: { facebook: 'https://facebook.com/lahorecertifiedcars', website: 'https://example.com/lahore-certified' },
    },
    {
      id: 'repair-islamabad-rent-a-car',
      name: 'Islamabad Rent A Car Network',
      category: 'rent-a-car',
      city: 'Islamabad',
      area: 'Blue Area',
      address: 'Jinnah Avenue, Blue Area, Islamabad',
      lat: 33.7077,
      lng: 73.0498,
      distanceKm: 5.6,
      rating: 4.6,
      reviews: 96,
      completedJobs: 430,
      communityVotes: 141,
      responseTime: '20 min',
      verified: true,
      openNow: true,
      specialties: ['Rent a car', 'Self drive', 'Chauffeur', 'Airport pickup'],
      socialLinks: { instagram: 'https://instagram.com/isbrentacar', whatsapp: 'https://wa.me/923005551212' },
    },
  ],
  repairShopReviews: [
    {
      id: 'repair-review-clifton-1',
      shopId: 'repair-clifton-auto-care',
      userId: 'seed-buyer-1',
      userName: 'Karachi Driver',
      rating: 5,
      serviceType: 'Inspection',
      title: 'Clear inspection and photos',
      body: 'They explained suspension noise clearly and shared short videos before starting work.',
      vehicle: 'Toyota Fortuner 2019',
      helpfulCount: 12,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    {
      id: 'repair-review-rental-1',
      shopId: 'repair-islamabad-rent-a-car',
      userId: 'seed-buyer-2',
      userName: 'Airport Customer',
      rating: 4,
      serviceType: 'Airport pickup',
      title: 'Clean car, verified driver',
      body: 'Good rental experience. They should upload more interior walkaround videos.',
      vehicle: 'Toyota Corolla rental',
      helpfulCount: 5,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
  ],
  repairShopQuestions: [
    {
      id: 'repair-question-clifton-1',
      shopId: 'repair-clifton-auto-care',
      userId: 'seed-buyer-3',
      userName: 'Civic Owner',
      question: 'Can you inspect a Civic turbo before auction bidding?',
      answer: 'Yes, we can do a pre-bid inspection with photos, scanner report, and short video notes.',
      answeredByName: 'Clifton Auto Care',
      answeredAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
      status: 'answered',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    },
  ],
  serviceVideos: [
    {
      id: 'service-video-clifton-1',
      providerType: 'repair_shop',
      providerId: 'repair-clifton-auto-care',
      ownerId: 'seed-seller',
      title: 'Pre-purchase inspection walkaround',
      description: 'A sample video showing how the workshop records service findings for buyers.',
      serviceType: 'Inspection',
      videoUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
      thumbnailUrl: 'https://placehold.co/700x420?text=Inspection+Video',
      status: 'published',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    },
    {
      id: 'service-video-rental-1',
      providerType: 'repair_shop',
      providerId: 'repair-islamabad-rent-a-car',
      ownerId: 'seed-seller',
      title: 'Rental fleet walkaround',
      description: 'Rent-a-car providers can show available vehicles, cleanliness, driver options, and pickup process.',
      serviceType: 'Rent a Car',
      videoUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
      thumbnailUrl: 'https://placehold.co/700x420?text=Rental+Fleet+Video',
      status: 'published',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    },
  ],
  editorialWriters: [
    {
      id: 'writer-marketwatcher',
      userId: 'writer-marketwatcher',
      name: 'MarketWatcher',
      role: 'Verified Market Analyst',
      city: 'Karachi',
      avatar: 'https://placehold.co/160x160?text=MW',
      verified: true,
      bio: 'Tracks Pakistan used-car price movement, auction pressure, and dealer inventory signals.',
      socials: { x: '@marketwatcherpk', website: 'https://example.com/marketwatcher' },
      createdAt: new Date().toISOString(),
    },
    {
      id: 'writer-auctionpilot',
      userId: 'writer-auctionpilot',
      name: 'AuctionPilot',
      role: 'Verified Auction Writer',
      city: 'Lahore',
      avatar: 'https://placehold.co/160x160?text=AP',
      verified: true,
      bio: 'Writes bidding strategy, inspection prep, and seller reserve guidance.',
      socials: { instagram: '@auctionpilotpk' },
      createdAt: new Date().toISOString(),
    },
  ],
  editorialArticles: [
    {
      id: 'article-auction-checklist',
      slug: 'pre-bid-inspection-checklist-pakistan',
      title: 'The Pre-Bid Inspection Checklist Every Buyer Should Use',
      deck: 'Before placing a serious auction bid, buyers need a repeatable inspection routine.',
      category: 'Auction Tips',
      tags: ['auction', 'inspection', 'buyer protection'],
      authorId: 'writer-auctionpilot',
      authorName: 'AuctionPilot',
      authorRole: 'Verified Auction Writer',
      status: 'published',
      featured: true,
      heroImage: 'https://placehold.co/1200x640/0f172a/ffffff?text=Auction+Inspection+Checklist',
      readMinutes: 6,
      body: [
        'Auction bidding rewards preparation. The buyer who knows the car, documents, likely repairs, and walk-away price has an advantage.',
        'Start with ownership proof, title status, tax token, and transfer documents. Then inspect panels, engine, gearbox, suspension, tires, AC, electronics, and scanner report.',
        'Your bid ceiling should include hammer price, platform fee, transfer, transport, immediate service, tires, and a repair buffer.',
      ],
      views: 1480,
      likes: 126,
      bookmarks: 42,
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      id: 'article-installments-trend',
      slug: 'why-installments-are-trending-in-pakistan-car-market',
      title: 'Why Installments Are Becoming a Bigger Part of Pakistan\'s Car Market',
      deck: 'Rising prices have pushed buyers to think monthly payment first.',
      category: 'Installments',
      tags: ['installments', 'finance', 'market'],
      authorId: 'writer-marketwatcher',
      authorName: 'MarketWatcher',
      authorRole: 'Verified Market Analyst',
      status: 'published',
      featured: true,
      heroImage: 'https://placehold.co/1200x640/0f766e/ffffff?text=Car+Installments+Pakistan',
      readMinutes: 5,
      body: [
        'For many buyers, the search no longer starts with total price. It starts with what the household can safely pay every month.',
        'Marketplaces need filters for down payment, monthly installment, tenure, ownership transfer timing, and late-payment risk.',
        'The opportunity is not only financing. It is clarity.',
      ],
      views: 980,
      likes: 88,
      bookmarks: 31,
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    },
  ],
  editorialComments: [],
  sellerDrafts: [],
  checkouts: [],
  notifications: [],
  savedSearches: [],
  recommendationFeedback: [],
  disputes: [],
  reports: [],
};
